/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dao.ProductSearchDAO;

/**
 * MyEclipse Struts Creation date: 06-22-2013
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/loadAddReview" name="loadAddReviewForm"
 *                input="/index.jsp" scope="request" validate="true"
 * @struts.action-forward name="addReview" path="/addReview.jsp"
 */
public class LoadAddReviewAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		final ProductSearchDAO dao = new ProductSearchDAO();
		request.getSession().setAttribute("allProducts",
				dao.getAllProductDisplayNames());
		dao.closeConnection();
		return mapping.findForward("addReview");
	}
}