/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dao.ProductSearchDAO;
import entity.Press;

/**
 * MyEclipse Struts Creation date: 06-16-2013
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/loadSearchProduct" name="loadSearchProductForm"
 *                input="/index.jsp" scope="request" validate="true"
 */
public class LoadSearchProductAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		request.getSession().removeAttribute("availResult");
		request.getSession().removeAttribute("outfitResult");
		request.getSession().removeAttribute("bag");
		request.getSession().removeAttribute("shoes");
		request.getSession().removeAttribute("clothing");
		final ProductSearchDAO dao = new ProductSearchDAO();
		final List<String> brandNames = dao.getAllBrandNames();
		request.getSession().setAttribute("allBrands", brandNames);
		request.getSession().setAttribute("allSeasons", dao.getAllSeasons());
		request.getSession().setAttribute("allProducts",
				dao.getAllProductDisplayNames());
		final List<Press> presses = dao.getAllPresses();
		final Map<Long, String> allPresses = new HashMap<Long, String>();
		for (final Press p : presses) {
			allPresses.put(p.getId(), p.toUIDisplayString());
		}
		request.getSession().setAttribute("allPresses", allPresses);
		request.getSession().setAttribute("allPublishDates",
				dao.getAllPublishDates());
		dao.closeConnection();
		return mapping.findForward("initProductSearch");
	}
}