/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yourcompany.struts.form.SearchProductForm;

import dao.ProductSearchDAO;
import entity.Apparel;

/**
 * MyEclipse Struts Creation date: 06-16-2013
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/searchProduct" name="searchProductForm" scope="request"
 *                validate="true"
 */
public class SearchProductAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		request.getSession().removeAttribute("bag");
		request.getSession().removeAttribute("shoes");
		request.getSession().removeAttribute("clothing");
		SearchProductForm searchProductForm = (SearchProductForm) form;
		final ProductSearchDAO dao = new ProductSearchDAO();
		final List<Apparel> apparel = dao.findApparel(searchProductForm
				.getApparelSearchParams());
		dao.closeConnection();
		if (!apparel.isEmpty()) {
			// bag, shoes, or clothing
			request.getSession().setAttribute(
					searchProductForm.getApparelSearchParams().getType(),
					apparel);
		} else {
			final ActionErrors msg = new ActionErrors();
			msg.add("searchResult", new ActionError("noDataToDisplay"));
			saveErrors(request, msg);
		}
		return mapping.findForward("searchProduct");
	}
}