/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import ui.HottestAndBestApparelUIAdaptor;

import dao.ProductSearchDAO;
import entity.ReviewedApparel;

/**
 * MyEclipse Struts Creation date: 06-22-2013
 * 
 * XDoclet definition:
 * 
 * @struts.action input="/index.jsp" validate="true"
 * @struts.action-forward name="result" path="/bestAndMostRated.jsp"
 */
public class ShowBestAndMostRatedAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		request.getSession().removeAttribute("hottestApparel");
		request.getSession().removeAttribute("bestApparel");
		final ProductSearchDAO dao = new ProductSearchDAO();
		final List<ReviewedApparel> hottest = new ArrayList<ReviewedApparel>();
		final List<ReviewedApparel> best = new ArrayList<ReviewedApparel>();
		dao.findHottestApparel(30, hottest, best);
		dao.closeConnection();
		final List<HottestAndBestApparelUIAdaptor> hottestApparel = new ArrayList<HottestAndBestApparelUIAdaptor>();
		final List<HottestAndBestApparelUIAdaptor> bestApparel = new ArrayList<HottestAndBestApparelUIAdaptor>();
		for (final ReviewedApparel a : hottest) {
			hottestApparel.add(new HottestAndBestApparelUIAdaptor(a));
		}
		for (final ReviewedApparel a : best) {
			bestApparel.add(new HottestAndBestApparelUIAdaptor(a));
		}
		request.getSession().setAttribute("hottestApparel", hottestApparel);
		request.getSession().setAttribute("bestApparel", bestApparel);
		return mapping.findForward("result");
	}
}