/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-22-2013
 * 
 * XDoclet definition:
 * @struts.form name="addReviewForm"
 */
public class AddReviewForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** rate property */
	private Double rate;

	/** userName property */
	private String userName;

	/** productId property */
	private Long productId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		final ActionErrors errors = new ActionErrors();
		if(userName==null || userName.isEmpty())
		{
			errors.add("userName", new ActionError("errors.emptyUserName"));
		}
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
	}

	/** 
	 * Returns the rate.
	 * @return Double
	 */
	public Double getRate() {
		return rate;
	}

	/** 
	 * Set the rate.
	 * @param rate The rate to set
	 */
	public void setRate(Double rate) {
		this.rate = rate;
	}

	/** 
	 * Returns the userName.
	 * @return String
	 */
	public String getUserName() {
		return userName;
	}

	/** 
	 * Set the userName.
	 * @param userName The userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/** 
	 * Returns the productId.
	 * @return Long
	 */
	public Long getProductId() {
		return productId;
	}

	/** 
	 * Set the productId.
	 * @param productId The productId to set
	 */
	public void setProductId(Long productId) {
		this.productId = productId;
	}
}