/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import ui.ApparelAvailSearchParams;

/**
 * MyEclipse Struts Creation date: 06-19-2013
 * 
 * XDoclet definition:
 * 
 * @struts.form name="searchAvailForm"
 */
public class SearchAvailForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** productId property */
	private String productId;

	/** size property */
	private String size;

	private ApparelAvailSearchParams availSearchParams;

	/*
	 * Generated Methods
	 */

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		final ActionErrors errors = new ActionErrors();
		final Double doubleSize;
		if (size.isEmpty()) {
			doubleSize = null;
		} else {
			try {
				doubleSize = Double.valueOf(size);
				if (doubleSize < 0) {
					errors.add("size", new ActionError("errors.invalidSize"));
					return errors;
				}
			} catch (NumberFormatException e) {
				errors.add("size", new ActionError("errors.invalidSize"));
				return errors;
			}
		}
		availSearchParams = new ApparelAvailSearchParams(
				Long.valueOf(productId), doubleSize);
		return errors;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
	}

	/**
	 * Returns the productId.
	 * 
	 * @return String
	 */
	public String getProductId() {
		return productId;
	}

	/**
	 * Set the productId.
	 * 
	 * @param productId
	 *            The productId to set
	 */
	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getSize() {
		return size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	public ApparelAvailSearchParams getAvailSearchParams() {
		return availSearchParams;
	}
}