/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 06-20-2013
 * 
 * XDoclet definition:
 * 
 * @struts.form name="searchOutfitForm"
 */
public class SearchOutfitForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** productId property */
	private String productId;

	/*
	 * Generated Methods
	 */

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		if ("ALL".equals(productId)) {
			productId = null;
		}
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
	}

	/**
	 * Returns the productId.
	 * 
	 * @return String
	 */
	public String getProductId() {
		return productId;
	}

	/**
	 * Set the productId.
	 * 
	 * @param productId
	 *            The productId to set
	 */
	public void setProductId(String productId) {
		this.productId = productId;
	}
}